m/b/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    # path('', views.post_list, name='post_list'),
    path('', views.PostListView.as_view(), name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/',
         views.post_detail,
         name='post_detail'),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
]

m/m/urls.py
from django.urls import path, include
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('b/', include('b.urls', namespace='b')),
]

m/b/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse


# Create your models here.
class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset().filter(status='published')


class Post(models.Model):
    objects = models.Manager()  # The default manager.
    published = PublishedManager()  # Our custom manager.

    def get_absolute_url(self):
        return reverse('b:post_detail',
                       args=[self.publish.year,
                             self.publish.month,
                             self.publish.day,
                             self.slug])
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250,
                            unique_for_date='publish')
    author = models.ForeignKey(User, on_delete=models.CASCADE,
                               related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10,
                              choices=STATUS_CHOICES,
                              default='draft')

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return 'Comment by {} on {}'.format(self.name, self.post)

# Create your models here.

m/b/forms.py
from django import forms
from .models import Comment
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')

m/b/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView
from django.core.mail import send_mail
from .models import Post, Comment
from .forms import EmailPostForm, CommentForm


class PostListView(ListView):
    queryset = Post.published.all()
    context_object_name = 'posts'
    paginate_by = 3
    template_name = 'post/list.html'


def post_list(request):
    object_list = Post.objects.all()
    paginator = Paginator(object_list, 3)  # 3	posts	in	each	page
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the	first page
        posts = paginator.page(1)
    except EmptyPage:
        # If page is out of	range deliver last page	of results
        posts = paginator.page(paginator.num_pages)

    return render(request, 'post/list.html', {'page': page, 'posts': posts})


def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post,
                             status='published',
                             publish__year=year,
                             publish__month=month,
                             publish__day=day)

    # List of active comments for this post

    comments = post.comments.filter(active=True)

    new_comment = None

    if request.method == 'POST':

        # A comment was posted
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            # Create Comment object but don't save to database yet
            new_comment = comment_form.save(commit=False)
            # Assign the current post to the comment
            new_comment.post = post
            # Save the comment to the database
            new_comment.save()

    else:
        comment_form = CommentForm()
    return render(request, 'post/detail.html',
                  {'post': post,
                   'comments': comments,
                   'new_comment': new_comment,
                   'comment_form': comment_form})


def post_share(request, post_id):
    # Retrieve post by id
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False

    if request.method == 'POST':
        # Form was submitted
        form = EmailPostForm(request.POST)
        if form.is_valid():
            # Form fields passed validation
            cd = form.cleaned_data
            # ....send email
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = '{} ({}) recommends you reading "{}"'.format(cd['name'], cd['email'], post.title)
            message = 'Read	"{}" at {}\n\n{}\'s	comments: {}'.format(post.title, post_url, cd['name'],
                                                                           cd['comments'])
            send_mail(subject, message, 'admin@myblog.com', [cd['to']])
            sent = True


    else:
        form = EmailPostForm()
    return render(request, 'post/share.html', {'post': post, 'form': form, 'sent': sent})

# Create your views here.

m/b/templates/b/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}MY Blog{% endblock %}</title>
    <link href="{% static 'css/b.css' %}" rel="stylesheet">
</head>
<body>
    <div id="content">
        {% block content %}
        {% endblock %}
    </div>

    <div class="sidebar">
        <h2 class="m">MY BLOG</h2>
        <p>This is my blog.</p>
    </div>
</body>
</html>

m/b/templates/b/pagination.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <div class="pagination">
	    <span class="step-links">
	        {% if page.has_previous	%}
	            <a href="?page={{ page.previous_page_number	}}">Previous</a>
	        {% endif %}
	        <span class="current">
                Page {{	page.number	}}	of	{{ page.paginator.num_pages }}
	        </span>
	        {% if page.has_next	%}
	            <a href="?page={{ page.next_page_number	}}">Next</a>
	        {% endif %}
		</span>
    </div>

</body>
</html>

m/b/templates/post/detail.html
{% extends "b/base.html" %}
{% block title %}{{ post.title }}{% endblock %}

{{%	block	content	%}
	<h1 class="title">{{ post.title	}}</h1>
	<hr class="my-4">
	<p class="date">
	    Published {{ post.publish }} by	{{ post.author }}
	</p>
	<p class="subheading">{{ post.body|linebreaks }}</p>

    <p>
	    <a href = "{% url 'b:post_share' post.id %}" class="share">
			Share this post
		</a>
    </p>

	{% with comments.count as total_comments %}
		<h5>{{ total_comments }} comment{{ total_comments|pluralize }}</h5>
	{% endwith %}

	{% for comment in comments %}
		<div class="comment">
			<p class="info">
				Comment {{ forloop.counter }} by {{ comment.name }}
				{{ comment.created }}
			</p>
			{{ comment.body|linebreaks }}
		</div>
	{% empty %}
		<p> There are no comments yet.</p>
	{% endfor %}

	{% if new_comment %}
		<h2>Your comment has been added.</h2>
	{% else %}
		<h4>Add a new comment</h4>
		<form action="." method="post" class="form">
			{{ comment_form.as_p }}
			{% csrf_token %}
			<p ><input type="submit" value="Add comment"></p>
		</form>
	{% endif %}

{% endblock %}

m/b/templates/post/list.html
{% extends "b/base.html" %}
{% block title %}My Blog{% endblock %}

{% block content %}
    <h1>My Blog</h1>
    <hr class="my-4">
    {% if posts %}
        {% for post in posts %}
            <h2 class="post-heading">
                <a href="{{ post.get_absolute_url }}">
                    {{ post.title }}
                </a>
            </h2>
            <p class="date">
                published {{ post.publish }} by {{ post.author }}
            </p>
            <p class="subheading">
                {{ post.body|truncatewords:30|linebreaks }}
            </p>
        {% endfor %}
    {% endif %}
  	{% include "b/pagination.html" with page=page_obj %}
{% endblock %}

m/b/templates/post/share.html
{% extends "blog/base.html" %}

{% load crispy_forms_tags%}
{% block title %}Share a post{% endblock %}
{% block content %}
    {% if sent %}
        <h1>E-mail successfully	sent</h1>
		<p>
     	  "{{ post.title }}" was successfully sent to {{ form.cleaned_data.to }}.
		</p>
	{% else	%}
	    <h1>Share "{{ post.title }}" by	e-mail</h1>
		<hr class="my-4">
        <form action="." method="post" novalidate>
	 		{% csrf_token %}
			<div class="row">
				<div class="col-6">
					{{ form.name|as_crispy_field }}
				</div>
				<div class="col-6">
					{{ form.email|as_crispy_field }}
				</div>
			</div>
			{{ form.to|as_crispy_field }}
			{{ form.comments|as_crispy_field }}
		  <p class="button"><input type="submit" value="Send E-Mail"></p>
		</form>
	{% endif %}
{% endblock %}